[tool.mypy]
plugins = ["pydantic.mypy", "sqlmypy"]
mypy_path = [".venv/src/cm-api", ".venv/src/cm-intercom", ".venv/src/cm-constants", ".venv/src/cm-utils"]
follow_imports = "silent"
install-types = true
non_interactive = true
disallow_untyped_defs = true
#disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
#warn_return_any = true
warn_unused_ignores = true
show_error_codes = true
ignore_missing_imports = true
[[tool.mypy-autobahn.overrides]]
module = "mypy-autobahn.*"
ignore_missing_imports = true
[[tool.mypy-aioredis.overrides]]
module = "mypy-aioredis.*"
ignore_missing_imports = true
[[tool.mypy-elasticapm.overrides]]
module = "mypy-elasticapm.*"
ignore_missing_imports = true
[[tool.mypy-PIL.overrides]]
module = "mypy-PIL.*"
ignore_missing_imports = true
[[tool.mypy-babel.overrides]]
module = "mypy-babel.*"
ignore_missing_imports = true
